set shell := ["bash", "-uc"]

symbols_path := "build/app/intermediates/merged_native_libs/release/mergeReleaseNativeLibs/out/lib"

# Clean build artifacts
clean:
    flutter clean

# Analyze source code
analyze:
    flutter analyze --no-pub .

# Format source code
format:
    dart format .

# Build a release for android
build-android-release:
    flutter build appbundle --release

# Create debug symbols zip file
create-debug-symbols:
    cd {{symbols_path}} && zip -r symbols.zip .
    mv {{symbols_path}}/symbols.zip .
