name: CICD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  # linting stages
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
      - name: Install dependencies
        run: flutter pub get --directory ./flutter
      - name: Anayze source code
        run: flutter analyze --no-pub --no-preamble ./flutter/lib
