name: Gh-Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
      - name: Create web app on Github gh pages
        uses: bluefireteam/flutter-gh-pages@v9
        with:
          workingDir: flutter
          baseHref: /djambi/
          webRenderer: canvaskit
